/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tejas_finalv2_rtstack_RTStack */

#ifndef _Included_com_example_tejas_finalv2_rtstack_RTStack
#define _Included_com_example_tejas_finalv2_rtstack_RTStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doCreateNewSession
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doCreateNewSession
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doFreeSession
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doFreeSession
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doConnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doConnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doEndSession
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doEndSession
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doSetTxRawDataCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doSetTxRawDataCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doSetRxStreamDataCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doSetRxStreamDataCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doSetRxControlDataCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doSetRxControlDataCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doSetErrorCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doSetErrorCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doSetStateChangeCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doSetStateChangeCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doSetDebugCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doSetDebugCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doOneSecondTick
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doOneSecondTick
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doPutTxStreamData
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doPutTxStreamData
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doPutTxControlData
 * Signature: (JB[BI)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doPutTxControlData
  (JNIEnv *, jclass, jlong, jbyte, jbyteArray, jint);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    doPutRxRawData
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_doPutRxRawData
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_example_tejas_finalv2_rtstack_RTStack
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_tejas_finalv2_rtstack_RTStack_initIds
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
